// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ErrorNotFound: typeof import('./pages/ErrorNotFound.vue')['default']
    IndexPage: typeof import('./pages/IndexPage.vue')['default']
    MainLayout: typeof import('./layouts/MainLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
